config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#index'

  resources :users, :apt_buzzers

  # Basic Site Navigation
  match '/sign_up',       to: 'users#new',    		via: 'get'
  match '/my_profile',    to: 'users#show',			via: 'get'
  match '/settings',      to: 'users#edit',			via: 'get'
  match '/sign_in',       to: 'sessions#new',		via: 'get'
  match '/sign_out',      to: 'sessions#destroy',   via: 'get'

  # Twilio Number - Controller/Actions 
  post 'twilio/voice'    			   => 'twilio#voice'
  post 'twilio/message'  			   => 'twilio#message'
  post 'twilio/initial_menu_response'  => 'twilio#initial_menu_response'
  post 'twilio/password_validation'    => 'twilio#password_validation'

  
end

app/views/layouts/shared/_footer.html.erb
<footer>
 <small>
  <%= link_to 'Buzz Me In', root_path %>
 </small>
  <nav>
   <ul>
    <!-- <li></li> -->
   </ul>
  </nav>
</footer>

app/views/layouts/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/shared/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Users', users_path('about') %></li>
<li><%= link_to 'Apt Buzzer App', apt_buzzers_path('about') %></li>
<%= render 'layouts/shared/sign_in_out_links' %>

app/views/layouts/shared/_sign_in_out_links.html.erb
<% if current_user %>
<li>
 <div class="dropdown dropdown-navbar-user-tab" id="navbar-user-tab">
  <a data-toggle="dropdown" class="borderless" href="#">
   <div class="navbar-user-tab-wrapper">
    <div class="navbar-user-tab-img">
     <%= image_tag "dc.jpg", :class=>"img-responsive" %>
    </div>
    <div class="navbar-user-tab-user-name" >
     <%= current_user.first_name %>
    </div>
    <div class="navbar-user-tab-grey-bk"></div>
   </div>   
  </a>
   <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <li>
     <%= link_to 'Profile Settings', root_path %>
    </li>
    <li>
     <%= link_to 'My Progress', root_path %>
    </li>
   <li class="divider"></li>
    <li>
     <%= link_to "Log Out",  sign_out_path, :id => "sign_out" %>
    </li>
   </ul>
 </div> <!-- end of drop down --> 
</li>
<% else %>
<li>
  <%= link_to "Sign In",  sign_in_path, :class=>"" %>
</li>
<% end %>