config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#index'

  resources :users, :apt_buzzers

  # Basic Site Navigation
  match '/sign_up',       to: 'users#new',    		via: 'get'
  match '/my_profile',    to: 'users#show',			via: 'get'
  match '/settings',      to: 'users#edit',			via: 'get'
  match '/sign_in',       to: 'sessions#new',		via: 'get'
  match '/sign_out',      to: 'sessions#destroy',   via: 'get'

  # Twilio Number - Controller/Actions 
  post 'twilio/voice'    			   => 'twilio#voice'
  post 'twilio/message'  			   => 'twilio#message'
  post 'twilio/initial_menu_response'  => 'twilio#initial_menu_response'
  post 'twilio/password_validation'    => 'twilio#password_validation'

  
end

app/models/apt_buzzer.rb
class AptBuzzer < ActiveRecord::Base
end

app/controllers/apt_buzzers_controller.rb
class AptBuzzersController < ApplicationController
  before_action :set_apt_buzzer, only: [:show, :edit, :update, :destroy]

  # GET /apt_buzzers
  # GET /apt_buzzers.json
  def index
    @apt_buzzers = AptBuzzer.all
  end

  # GET /apt_buzzers/1
  # GET /apt_buzzers/1.json
  def show
  end

  # GET /apt_buzzers/new
  def new
    @apt_buzzer = AptBuzzer.new
  end

  # GET /apt_buzzers/1/edit
  def edit
  end

  # POST /apt_buzzers
  # POST /apt_buzzers.json
  def create
    @apt_buzzer = AptBuzzer.new(apt_buzzer_params)

    respond_to do |format|
      if @apt_buzzer.save
        format.html { redirect_to @apt_buzzer, notice: 'Apt buzzer was successfully created.' }
        format.json { render :show, status: :created, location: @apt_buzzer }
      else
        format.html { render :new }
        format.json { render json: @apt_buzzer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apt_buzzers/1
  # PATCH/PUT /apt_buzzers/1.json
  def update
    respond_to do |format|
      if @apt_buzzer.update(apt_buzzer_params)
        format.html { redirect_to @apt_buzzer, notice: 'Apt buzzer was successfully updated.' }
        format.json { render :show, status: :ok, location: @apt_buzzer }
      else
        format.html { render :edit }
        format.json { render json: @apt_buzzer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apt_buzzers/1
  # DELETE /apt_buzzers/1.json
  def destroy
    @apt_buzzer.destroy
    respond_to do |format|
      format.html { redirect_to apt_buzzers_url, notice: 'Apt buzzer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apt_buzzer
      @apt_buzzer = AptBuzzer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apt_buzzer_params
      params[:apt_buzzer]
    end
end

app/helpers/apt_buzzers_helper.rb
module AptBuzzersHelper
end

app/views/apt_buzzers/_form.html.erb
<%= form_for(@apt_buzzer) do |f| %>
  <% if @apt_buzzer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apt_buzzer.errors.count, "error") %> prohibited this apt_buzzer from being saved:</h2>

      <ul>
      <% @apt_buzzer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apt_buzzers/edit.html.erb
<h1>Editing apt_buzzer</h1>

<%= render 'form' %>

<%= link_to 'Show', @apt_buzzer %> |
<%= link_to 'Back', apt_buzzers_path %>

app/views/apt_buzzers/index.html.erb
<h1>Listing apt_buzzers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apt_buzzers.each do |apt_buzzer| %>
      <tr>
        <td><%= link_to 'Show', apt_buzzer %></td>
        <td><%= link_to 'Edit', edit_apt_buzzer_path(apt_buzzer) %></td>
        <td><%= link_to 'Destroy', apt_buzzer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apt buzzer', new_apt_buzzer_path %>

app/views/apt_buzzers/new.html.erb
<h1>New apt_buzzer</h1>

<%= render 'form' %>

<%= link_to 'Back', apt_buzzers_path %>

app/views/apt_buzzers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_apt_buzzer_path(@apt_buzzer) %> |
<%= link_to 'Back', apt_buzzers_path %>